Don't store documents non historical settings in order meta
wpovernight/woocommerce-pdf-invoices-packing-slips pull request #285
Opened 2022-01-10 17:12 UTC by alexmigf

closes #257

2022-01-10 18:22 UTC, Spreeuw commented
The issue is merely about the _save_ process, and I think your approach is so different from the original that it opens a lot of other potential issues.

I propose that we focus on filtering the data being saved, and if you think there are other areas that need improvement, please open a separate issue for that, describing what you would like to improve.
A simple `array_filter()` would probably suffice here: https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/3d765bd80cf2f6f35a2ab9eff661c389f7d8f4e9/includes/documents/abstract-wcpdf-order-document.php#L152-L154

2022-01-11 12:27 UTC, Spreeuw requested changes

2022-01-11 12:31 UTC, alexmigf commented on includes/documents/abstract-wcpdf-order-document.php
> +			$settings = array_diff_key( $settings, array_flip(  $non_historical_settings ) );
Ok

2022-01-11 12:51 UTC, Spreeuw commented on includes/documents/abstract-wcpdf-order-document.php
> +			$settings = array_diff_key( $settings, array_flip(  $non_historical_settings ) );
@alexmigf You _still_ modify the `$settings` value, which is your _return_ value that should not be modified! See my comment above.

2022-01-11 12:59 UTC, Spreeuw approved these changes
Code looks good, I've added @YordanSoares to review for functional tests

2022-01-19 19:19 UTC, YordanSoares approved these changes
✔️ Looks good to me!

2022-01-19 21:05 UTC, merged