Dompdf ^2.0 upgrade
wpovernight/woocommerce-pdf-invoices-packing-slips pull request #383
Opened 2022-06-23 14:27 UTC by alexmigf

closes #382

Needs testing from @YordanSoares

2022-06-23 14:36 UTC, Spreeuw commented
@alexmigf to be clear: this is still in draft because it's not ready for review by @YordanSoares , correct?
Some questions that came to mind when I saw the dompdf changelog:

1. We have a setting "Use alternative HTML5 parser to parse HTML" is that setting (or its behavior) affected by the new HTML parser?
2. I guess migration of the font cache data to the new JSON format is required (as part of the upgrade routines), as well as our `Font_Synchronizer` class, correct?
3. Since dompdf has breaking changes, should we also bump our plugin version to 3.0?

2022-06-23 14:38 UTC, alexmigf commented
@Spreeuw no, I set as draft because is waiting testing not review. But I can change that if you want.

2022-06-24 07:57 UTC, alexmigf commented
@Spreeuw 

1) Seems to be working fine.
2) I guess so.
3) I think we should.

2022-06-24 08:13 UTC, Spreeuw commented
Regarding the HTML parser, it seems the `isHtml5ParserEnabled` option is no longer used at all though, so the setting wouldn't have any effect?

This is the current code:
https://github.com/dompdf/dompdf/blob/165ad28f0291d7ba257b236caaa4b442a28d2150/src/Dompdf.php#L473-L489

And the old code where it used the option:
https://github.com/dompdf/dompdf/blob/5f52622e79202dd469fdd3053f141d30e0901808/src/Dompdf.php#L505-L511

I no longer find any code using the `isHtml5ParserEnabled` option in dompdf

2022-06-24 10:01 UTC, Spreeuw commented
That's just the setters and the getters in the `Options` object, not being actually used, is it?

2022-06-24 10:07 UTC, alexmigf commented
No, doesn't seem to be used.

2022-06-24 10:38 UTC, alexmigf commented
They are using this library now: https://github.com/Masterminds/html5-php

2022-06-24 10:56 UTC, Spreeuw commented
> They are using this library now: https://github.com/Masterminds/html5-php

That replaces `DOMDocument` from the old code ([source](https://github.com/dompdf/dompdf/blob/5f52622e79202dd469fdd3053f141d30e0901808/src/Dompdf.php#L512-L518)). The alternative parser has been removed completely. So we should also remove the option.

2022-06-27 13:15 UTC, alexmigf commented
## Test 1

1. Using `main` branch, check the `uploads/wpo_wcpdf_*/fonts` directory for:
    1.1 PHP cache file is present
    1.2 Plugin fonts are present
2. Change to this PR branch and simulate the plugin upgrade to version `3.0.0`:
    2.1 Legacy PHP cache file is deleted :heavy_check_mark: 
    2.2 New JSON cache file is created with only the plugin fonts :heavy_check_mark:

## test 2

1. Using this PR branch only, simulating a new install:
    1.1 New JSON cache file is created with the plugin fonts
    1.2 Plugin fonts are copied

2022-06-27 16:42 UTC, Spreeuw requested changes
In your test you write this:

> 2.2 New JSON cache file is created with only the plugin fonts ✔️

But should this include the local (user installed) fonts too? Have you confirmed that the user installed fonts are correctly loaded after the migration? I'm asking because the `.dist` part in the JSON filename seems incorrect to me, but maybe I'm wrong.

2022-06-27 16:42 UTC, Spreeuw commented on includes/class-wcpdf-font-synchronizer.php
> +		$cacheData   = json_encode( $local_fonts );
dompdf uses `JSON_PRETTY_PRINT`, which I think is nice to copy here too!

2022-06-27 16:42 UTC, Spreeuw commented on includes/class-wcpdf-font-synchronizer.php
> +	public $font_cache_filename = "installed-fonts.dist.json";
I think this shouldn't be `.dist`, right? See:
https://github.com/dompdf/dompdf/blob/79573d8b8a141ec8a17312515de8740eed014fa9/src/FontMetrics.php#L36

2022-06-28 07:38 UTC, alexmigf commented on includes/class-wcpdf-install.php
> +		}
You mean the cache file replacement?

2022-06-28 07:54 UTC, Spreeuw commented on includes/class-wcpdf-install.php
> +		}
yes, moving from JSON to PHP

2022-06-28 09:09 UTC, alexmigf commented on includes/class-wcpdf-install.php
> +		}
Shouldn't be the contrary? From PHP to JSON? But that is already triggered by the `copy_fonts` when `$merge_with_local` is set to `true`.

2022-06-28 10:10 UTC, alexmigf commented
> But should this include the local (user installed) fonts too? Have you confirmed that the user installed fonts are correctly loaded after the migration? I'm asking because the .dist part in the JSON filename seems incorrect to me, but maybe I'm wrong.

Yes, you're right, shouldn't have the `dist` part. User local fonts are migrated as well.

2022-06-28 10:52 UTC, Spreeuw requested changes

2022-06-28 10:52 UTC, Spreeuw commented on includes/class-wcpdf-install.php
> +			WPO_WCPDF()->main->copy_fonts( $font_path, true );
as you correctly pointed out in previous comments, this is already done earlier in this method:
https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/de3f055345804a78a51fa043ba01333e0a00fd50/includes/class-wcpdf-install.php#L218
so we don't need to repeat it here.

2022-06-28 15:11 UTC, YordanSoares commented
I ran the same test that @alexmigf posted [here](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/pull/383#issuecomment-1167339914), and both the updating and new installation tests seems to be working well.

However, after the updating process, both `dompdf_font_family_cache.php` and `installed-fonts.json` seem to remain in the folder. I saw that the legacy PHP cache file is deleted only if you click on the **Reinstall fonts** button.

2022-06-28 16:51 UTC, YordanSoares commented
@alexmigf I installed the `main` branch, and then update the plugin manually with the branch from this PR.

2022-06-28 17:14 UTC, YordanSoares commented
@alexmigf I ran another test installing the `main `branch, and then update the plugin manually (under **Plugins > Add new > Upload plugin**) with the branch from this PR, and the `dompdf_font_family_cache.php` is not deleted in this step.

Also, I realized that `installed-fonts.json` is not created just after the update, but when a PDF document is requested. I'm not sure if this is the expected behavior.

2022-06-28 20:07 UTC, alexmigf commented
@YordanSoares did you changed the plugin version to 3.0.0?

2022-06-28 20:27 UTC, YordanSoares commented
@alexmigf that did the trick: Sorry for the mess! When I read the instructions to run the tests, I missed the part in which you mention the version change.

2022-06-28 20:29 UTC, YordanSoares approved these changes

2022-06-29 07:44 UTC, alexmigf commented
@YordanSoares I think you still need to check if aren't any changes in the PDF output for each template.

2022-06-30 10:42 UTC, Spreeuw approved these changes

2022-06-30 11:50 UTC, merged