Check if HTML is escaped properly before echoing
wpovernight/woocommerce-pdf-invoices-packing-slips pull request #408
Opened 2022-10-05 13:56 UTC by alexmigf

closes #407

2022-10-05 13:59 UTC, alexmigf commented
@YordanSoares @dwalkerpriv @dpeyou could you please test this changes and let me know if you find any glitch in the PDFs or in the settings?

2022-10-05 14:28 UTC, dwalkerpriv commented
@alexmigf seems fine for me. anything specific i should check?

2022-10-05 14:37 UTC, alexmigf commented
@dwalkerpriv just to a overall check, printing every data as possible in the PDF and see it everything works as normal. Also try to save/update some settings.

2022-10-05 14:54 UTC, DavidAnderson684 approved these changes
@alexmigf Approved - but I think I failed to clarify: they're not threatening to review this plugin. It's only the ones that they closed that have to be reviewed. For the ones still open, they've only requested the change of name.

2022-10-20 08:37 UTC, Terminator-Barbapapa requested changes

2022-10-20 08:37 UTC, Terminator-Barbapapa commented on templates/Simple/invoice.php
> +					<span class="item-meta"><?php echo esc_html( $item['meta'] ); ?></span>
Should be `wp_kses_post()`.  Item meta HTML is now escaped.

<img width="659" alt="Schermafbeelding 2022-10-20 om 10 34 37" src="https://user-images.githubusercontent.com/19350150/196899189-dcd7f190-1b5e-418e-a53a-7355bd6e6224.png">

2022-10-20 08:37 UTC, Terminator-Barbapapa commented on templates/Simple/packing-slip.php
> +					<span class="item-meta"><?php echo esc_html( $item['meta'] ); ?></span>
Should be `wp_kses_post()`.

2022-10-20 13:37 UTC, YordanSoares approved these changes
## Invoice:
![image](https://user-images.githubusercontent.com/38109855/196963564-bd051570-9fe0-4158-a920-f2191630adb0.png)

## Packing Slip:
![image](https://user-images.githubusercontent.com/38109855/196963671-3be38f80-0187-4c53-9be4-a57c643722f7.png)

2022-10-24 08:42 UTC, merged