HPOS compatibility
wpovernight/woocommerce-pdf-invoices-packing-slips pull request #427
Opened 2022-10-25 13:09 UTC by alexmigf

closes #420

### How to test?

You can test HPOS now using WooCommerce version 7.1, no need to install a special version anymore. You should follow this steps: https://developer.woocommerce.com/2022/09/16/high-performance-order-storage-call-for-testing-vol-2/#download-and-install

HPOS Sync is still much under development, it might not work as expected, I also had issues with it which I posted here: https://github.com/woocommerce/woocommerce/issues/34981

Desired testing setups:

* Existing WC <=7.0 setup + WC 7.1 upgrade + HPOS **enabled** + Sync **enabled** (can have issues)
* New WC 7.1 setup + HPOS **enabled** + Sync **disabled**
* Existing WC <7.1 setup + HPOS **disabled**
* New WC 7.1 setup + HPOS **disabled**

By "existing" I mean older versions of WC prior to 7.1 with orders created in the `wp_posts` table.

2022-11-15 16:10 UTC, DavidAnderson684 reviewed
(I've only read the code, not tried to run it).

2022-11-15 16:10 UTC, DavidAnderson684 commented on includes/class-wcpdf-admin.php
> +		if ( defined( 'WC_VERSION' ) && version_compare( WC_VERSION, '7.1', '>=' ) ) {
@alexmigf Why is the condition and branching needed? Presumably the actions/filters are only called when needed, so they don't need to be conditional.

2022-11-15 16:10 UTC, DavidAnderson684 commented on includes/class-wcpdf-admin.php
> +		$screen = wc_get_container()->get( CustomOrdersTableController::class )->custom_orders_table_usage_is_enabled() ? wc_get_page_screen_id( 'shop-order' ) : 'shop_order';
@alexmigf Won't there be a fatal error for the non-existent class `CustomOrdersTableController` before WC 7.1?

2022-12-02 15:51 UTC, Terminator-Barbapapa commented on assets/css/order-styles.css
>  }
There is still a difference between the buttons pre-HPOS and after. The icons are not correctly centered.

Before:
<img width="157" alt="Schermafbeelding 2022-12-02 om 16 45 32" src="https://user-images.githubusercontent.com/19350150/205331499-d5eb4b7c-ee3e-44d7-a713-ee22ecbba5dc.png">

After:
<img width="153" alt="Schermafbeelding 2022-12-02 om 16 45 24" src="https://user-images.githubusercontent.com/19350150/205331523-3d49b050-482d-4f39-ab80-abd9400ec59b.png">

2022-12-16 13:52 UTC, Terminator-Barbapapa requested changes

2022-12-16 15:37 UTC, alexmigf commented on assets/css/order-styles.css
> -}
Ouch

2022-12-28 18:01 UTC, passatgt commented
Bulk actions handling is different with HPOS too: https://github.com/woocommerce/woocommerce/pull/35442

2023-01-05 09:15 UTC, alexmigf commented
@passatgt thank you, I will take a look.

2023-01-09 13:05 UTC, Terminator-Barbapapa approved these changes

2023-01-10 13:14 UTC, dpeyou commented
So far, the only error that I encounter is with HPOS enabled + Sync enabled. In this instance:
- A certain order never appears as generated
- Each time I refresh the page when viewing this invoice, the Invoice number increments by 1

Invoice has already been generated, but the invoice number doesn't appear & the invoice icon doesn't have the green tick
![2023-01-09_21-15](https://user-images.githubusercontent.com/74280840/211560729-5108a9a7-c810-49f5-bb25-f22dad80fe03.png)
![2023-01-09_21-15_1](https://user-images.githubusercontent.com/74280840/211560781-4e215a83-fdfb-4d13-b613-5d8f9bc489c2.png)
On page refresh
![2023-01-09_21-15_2](https://user-images.githubusercontent.com/74280840/211560790-597f9472-77ad-496d-a044-bacf83e88831.png)

2023-01-10 13:49 UTC, dpeyou commented
I don't know how relevant this is, but for order #113 that I mentioned in my previous comment, when I disabled HPOS, I noticed that only for this particular order, the Invoice number disappeared (from Orders screen) and the green tick on the invoice number was gone. This didn't happen with any other order. When I generated the invoice, it incremented by 1: In my previous comment I stopped at 14. This time, the newly generated number is 15. When I refresh the page however, it does not increment the Invoice number :+1:

2023-01-10 14:13 UTC, alexmigf commented
Sync is not ready yet, almost sure that document meta wasn't saved in that order. If you didn't encounter other issues without sync it should be ok.

2023-01-10 14:23 UTC, dpeyou approved these changes

2023-01-10 14:38 UTC, dwalkerpriv commented
It won't work with my installation PDF invoices. Is there a particular version I should be using? I've updated to the latest version

![Screenshot 2023-01-10 093539](https://user-images.githubusercontent.com/62675729/211580329-c15dbc27-14dd-463f-b4ac-3b943f2a1e56.png)
![Screenshot 2023-01-10 093550](https://user-images.githubusercontent.com/62675729/211580336-2f79f0db-4207-4499-9a65-9cc8532332d1.png)

2023-01-11 15:02 UTC, dwalkerpriv commented
i haven't had any issues printing the data with:
- sync option on
- sync option off
- HPOS on
- HPOS off

![Screenshot 2023-01-11 092717](https://user-images.githubusercontent.com/62675729/211838416-e8b2b2bf-a9bf-498f-97f5-2a37473aa6cd.png)

![Screenshot 2023-01-11 093433](https://user-images.githubusercontent.com/62675729/211838420-98dfcd62-a8f1-476b-abb9-ee46bb3d6d38.png)

2023-01-11 18:49 UTC, dwalkerpriv approved these changes

2023-01-12 14:29 UTC, jhosagid7 commented
# HPOS compatibility

I also had no problems printing the data

Just to mention that at the beginning I had installed the plugins "PDF Invoices", "Stripe" and it showed me this warning:
![Advertiencia-plugin-existentes](https://user-images.githubusercontent.com/13604839/212088585-fb571349-5d17-48fd-84c1-a1b3ffd42b03.png)

After I disabled those plugins, it did show me the option for "High Performance Order Storage":
![habilitada la opcion despues de desactivar los plugins](https://user-images.githubusercontent.com/13604839/212089128-d8cb9e05-7acc-44cc-ab4e-8dcf69b247d0.png)


- Existing WC <=7.0 setup + WC 7.1 upgrade + HPOS enabled + Sync enabled (can have issues) ✔️ 
- New WC 7.1 setup + HPOS enabled + Sync disabled ✔️ 
- Existing WC <7.1 setup + HPOS disabled ✔️ 
- New WC 7.1 setup + HPOS disabled ✔️ 

![invoice](https://user-images.githubusercontent.com/13604839/212092708-24386aad-bfe7-4da7-a8db-4f9954490f83.png)

![Packing slips](https://user-images.githubusercontent.com/13604839/212092742-2ee7c29a-094d-45ac-8fe7-cfeec9e81071.png)

2023-01-12 14:30 UTC, jhosagid7 approved these changes

2023-01-13 00:11 UTC, YordanSoares approved these changes
Tests performed:
1. Installed WooCommerce and created 3 orders using the WordPress posts table;
2. Created PDF invoices for the 3 orders created in the previous step;
3. Enabling HPOS, created new High-Performance Order tables, and selected the WooCommerce order tables as default data store;
4. Created 3 new orders and PDF invoices for these orders;
5. All the orders and PDF invoices opens correctly.

The only different thing I realized is the icon update: 

![image](https://user-images.githubusercontent.com/38109855/212206889-dc74eec8-932f-45e4-a597-0a121833d399.png)

2023-01-13 08:39 UTC, alexmigf commented
@YordanSoares did you test the bulk action?

2023-01-13 10:56 UTC, YordanSoares commented
@alexmigf yes, it works smoothly, to open existing and generate new documents.

2023-01-13 11:13 UTC, merged