New: implements autoloader for plugin classes
wpovernight/woocommerce-pdf-invoices-packing-slips pull request #548
Opened 2023-07-14 10:12 UTC by alexmigf

closes #544

2023-07-17 03:33 UTC, MohamadNateqi requested changes

2023-07-17 14:01 UTC, MohamadNateqi approved these changes
Perfect job, Thanks!

2023-08-12 21:24 UTC, Terminator-Barbapapa approved these changes

2023-08-14 15:02 UTC, YordanSoares approved these changes
LGTM! 🚀

2023-08-14 15:18 UTC, merged

2023-08-14 15:56 UTC, alexmigf commented
@szepeviktor sure