New: document link access type implementation
wpovernight/woocommerce-pdf-invoices-packing-slips pull request #562
Opened 2023-08-14 14:13 UTC by alexmigf

closes #561

This PR introduces a new Status tab setting, which replaces the old "Guest Access":

![Screenshot from 2023-08-15 12-36-33](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/assets/533273/0f47bfa5-ee1f-468e-9cdf-3f5c7227e96a)

The 3 options are:

* **Logged in (recommended)**: it's the default and behaves exactly as before without the 'Guest access' enabled. A user must be logged in to access the document in the admin panel, and in the frontend must be the order owner. Uses nonce.
* **Guest**: behaves exactly as before with the order key, but this time it can also behave as "Logged in", if the user is logged in using a nonce.
* **Full**: is like 'Guest' but without checking the logged in status, it always use the order key instead of nonce.

A migration is also in place for previous versions of the plugin, passing the previous setting value if exists, to the new key.

2023-08-14 18:59 UTC, dwalkerpriv approved these changes
Works on my end.

A small correction in the description:

'By default, documents can only be accessed when logged in, from **the** admin panel or customer account. You could also give access permissions to guest customers, or full permission to everyone with a document link.'

I think a 'the' should be added before the 'admin panel'

2023-08-15 08:57 UTC, MohamadNateqi requested changes

2023-08-15 08:57 UTC, MohamadNateqi commented on includes/settings/class-wcpdf-settings-debug.php
> +						'logged_in' => __( 'Logged in (recommended)' , 'woocommerce-pdf-invoices-packing-slips' ),
WPCS - space before the comma

2023-08-15 08:57 UTC, MohamadNateqi commented on includes/class-wcpdf-main.php
> +				if ( ! $valid_nonce ) {
Maybe good to merge with the above if statement.

2023-08-15 08:57 UTC, MohamadNateqi commented on includes/class-wcpdf-main.php
> +				if ( ! $order ) {
Shouldn't this condition be at first?

2023-08-15 09:10 UTC, MohamadNateqi approved these changes
LGTM!

2023-08-15 11:09 UTC, YordanSoares reviewed
These are the tests I had run:

1. A new installation: It worked well for all the options ✅ 
2. Updating an existing installation: The migration was not made for the existing public release (v3.5.6) ⚠️ 
3. Tested the code snippet to add the download link on the thank-you page ([here](https://docs.wpovernight.com/woocommerce-pdf-invoices-packing-slips/download-link-on-the-thank-you-page/#enabling-guest-access)) ✅

2023-08-15 11:13 UTC, alexmigf commented on includes/class-wcpdf-install.php
> +		if ( version_compare( $installed_version, '3.5.7-dev-1', '<' ) ) {
No, you need to change here: https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/a30ed16ffc7b24d001b78d09848083d41feb6ada/woocommerce-pdf-invoices-packingslips.php#L24

2023-08-15 13:13 UTC, YordanSoares approved these changes
Alex, I updated the plugin version to test the migration and it worked well:

![image](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/assets/38109855/c0e7ee82-e1f4-44f7-b67c-dd01c0580f9d)

BTW, the improvement you just made to the description makes clearer what each option do: Great job!

2023-08-15 13:21 UTC, merged