Add new parameters to shortcode, and create a new shortcode
wpovernight/woocommerce-pdf-invoices-packing-slips pull request #579
Opened 2023-08-18 16:10 UTC by MohamadNateqi

2023-08-21 08:42 UTC, alexmigf requested changes

2023-08-21 08:42 UTC, alexmigf commented on includes/class-wcpdf-frontend.php
> +	public function generate_document_link_shortcode( $atts, $content = null, $tag = '' ) {
Maybe this function should be renamed to `generate_document_shortcode`?

2023-08-21 08:42 UTC, alexmigf commented on includes/class-wcpdf-frontend.php
> +	public function generate_document_link_shortcode( $atts, $content = null, $tag = '' ) {
Maybe rename `$tag` as `$shortcode_tag`? Like they indicate in docs.

2023-08-21 08:56 UTC, alexmigf approved these changes
LGTM!

2023-08-23 00:20 UTC, YordanSoares approved these changes
✅ LGTM!

2023-08-23 07:02 UTC, merged