#125 regular price conversion
wpovernight/woocommerce-pdf-invoices-packing-slips pull request #703
Opened 2024-01-29 10:36 UTC by BrunoPavlinic98

closes https://github.com/wpovernight/woocommerce-pdf-ips-templates/issues/125

I have implemented a function that will check if the order currency is the same as the default currency set in Woo Commerce, and will convert the prices to the order currency if order and default currencies are not the same. The prices will remain the same if:

The order currency and default currency are the same.
The order currency does not exist.
The order currency is not set up in the Woo Commerce Multi Currency settings.
This conversion should only affect the PDF values. The order, product, and order item data should not be touched.

We should also consider adding this kind of functionality to the price value, not only to regular price.
I have tested this with the following multi currency plugin - https://docs.villatheme.com/?item=woocommerce-multi-currency

Reproduction steps:

Add a Curcy WooCommerce Multi Currency plugin.
In the plugin settings, set 2 different currencies, one of them being the default one. Wait till the "Rate + Exchange Fee" is properly set up. It takes time for the plugin to retrieve this data, and if you click "Save" before the rates are set, the rates for all currencies will be 1 and the conversion won't make sense.
Add a new order, and try to create a pdf invoice for it. You will also need to setup that the invoice has the "Regular price" field.
The invoice should have the a regular price the same as the product regular price.
Change the default currency.
The regular price should be converted to the order currency.

The function works only for Curcy WooCommerce Multi Currency plugin, but can be extended to other plugins as well.

2024-01-29 13:30 UTC, BrunoPavlinic98 commented
After speaking with @YordanSoares, I was informed that Curcy plugin is the most used plugin for multicurrency features.
Here is the list of other plugins I have tested:
https://wordpress.org/plugins/wc-multi-currency/
https://wordpress.org/plugins/premmerce-woocommerce-multi-currency/
https://hr.wordpress.org/plugins/woocommerce-multilingual/

The listed plugins work in a different way than Curcy. They either store the order item prices in order item metadata table, with prices being converted, or they change the product price once a default currency is change. This is an issue because we can't know which prices need conversion and which are already converted on our invoices and packing slips. In each of the listed plugins, the product regular price was not converted.

2024-01-29 13:47 UTC, alexmigf requested changes

2024-01-29 13:47 UTC, alexmigf commented on includes/compatibility/class-wcpdf-compatibility-third-party-plugins.php
> +		$order = wc_get_order( $order_id );
You should check if the  order object exists.

2024-01-29 13:47 UTC, alexmigf commented on includes/compatibility/class-wcpdf-compatibility-third-party-plugins.php
> +		if($should_convert) {
You can add the filter directly here:

```php
if ( apply_filters( 'wpo_wcpdf_should_convert_price_to_order_currency', '__return_true' ) ) {
```

2024-01-29 13:47 UTC, alexmigf commented on includes/compatibility/class-wcpdf-compatibility-third-party-plugins.php
> +			if ( function_exists( 'wmc_get_price' ) && method_exists( $order, 'get_currency' ) && function_exists( 'get_woocommerce_currency' ) && get_woocommerce_currency() != $order->get_currency() ) {
`get_woocommerce_currency() !== $order->get_currency()`

2024-01-29 13:47 UTC, alexmigf commented on includes/compatibility/class-wcpdf-compatibility-third-party-plugins.php
> +	public function convert_to_order_currency( $raw_price, $order_id ) {
Maybe this should be renamed to `convert_price_to_order_currency`?

2024-01-29 13:47 UTC, alexmigf commented on includes/compatibility/class-wcpdf-compatibility-third-party-plugins.php
> +		return apply_filters( 'wpo_wcpdf_convert_to_order_currency', $price, $raw_price, $order_id );
This too? `wpo_wcpdf_convert_price_to_order_currency`

2024-01-29 13:47 UTC, alexmigf commented on includes/compatibility/class-wcpdf-compatibility-third-party-plugins.php
> +		return apply_filters( 'wpo_wcpdf_convert_to_order_currency', $price, $raw_price, $order_id );
And all the others missing `price` in the name.

2024-01-30 08:21 UTC, alexmigf commented on includes/compatibility/class-wcpdf-compatibility-third-party-plugins.php
> +		if($should_convert) {
No, it can be.

2024-01-30 10:54 UTC, BrunoPavlinic98 commented
I agree with all comments and I have fixed them.

2024-01-30 13:41 UTC, closed without merging