Fix: XSS vulnerability on Woo Checkout user input
wpovernight/woocommerce-pdf-invoices-packing-slips pull request #759
Opened 2024-04-01 15:24 UTC by alexmigf

2024-04-01 18:11 UTC, MohamadNateqi requested changes

2024-04-01 18:11 UTC, MohamadNateqi commented on includes/wcpdf-functions.php
> +	$allowed_tags = array_merge( apply_filters( 'wpo_wcpdf_sanitize_html_default_allowed_tags', array(
Do you think we should be concerned about the filter here?

2024-04-01 18:50 UTC, alexmigf commented on includes/wcpdf-functions.php
> +					$attributes_to_remove[] = $attr->nodeName;
My bad!

2024-04-01 18:50 UTC, alexmigf commented on includes/documents/abstract-wcpdf-order-document-methods.php
> +				$custom_field = array_map( function( $field ) {
Forgot that, thank you for catching it.

2024-04-02 09:27 UTC, alexmigf commented
@MohamadNateqi thank you for your precious testing!

2024-04-09 14:42 UTC, Terminator-Barbapapa commented on includes/documents/abstract-wcpdf-order-document-methods.php
> +			}
Shouldn't we put this outside the if/else statement, so it also works for refunds with a parent order that has no address?

2024-04-09 14:42 UTC, Terminator-Barbapapa commented on includes/documents/abstract-wcpdf-order-document-methods.php
> +				}
Same here.

2024-04-09 15:18 UTC, Terminator-Barbapapa approved these changes

2024-04-09 15:19 UTC, merged