Remove unwanted tags from `wpo_wcpdf_sanitize_html_content()`
wpovernight/woocommerce-pdf-invoices-packing-slips pull request #792
Opened 2024-05-14 13:32 UTC by MohamadNateqi

close #791

2024-05-16 13:54 UTC, MohamadNateqi commented on includes/wcpdf-functions.php
> +	$extra_wrapper = $dom->getElementsByTagName( 'div' )->item( 0 );
I think it should not happen, since I manually added a DIV element, but I'll add a check for that.

2024-05-16 14:22 UTC, alexmigf approved these changes
Works fine on my tests.

2024-05-22 12:58 UTC, Terminator-Barbapapa requested changes
It seems this is introducing additional whitespaces where there were none before. Like in the addresses:

<img width="322" alt="Scherm­afbeelding 2024-05-22 om 14 56 34" src="https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/assets/19350150/548a93e1-7377-4aed-9e73-53e158872976">

2024-05-27 11:21 UTC, MohamadNateqi commented
@Terminator-Barbapapa 

It's not that this PR is wrapping the text around whitespaces; the reason for that whitespaces, as you showed, is that we have the address field in a new line in our template without any HTML tag wrapping it:
https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/e2399ebe4ad708447c76da2b5bf7ae2d873a7177/templates/Simple/invoice.php#L55

The line breaks before and after outputting the address cause that. There were no whitespaces if it was immediately after the TD tag in one line.

But, the reason we hadn't this issue before this PR was that the DOM object was automatically wrapping the text around a P tag:

![image](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/assets/136313810/3180d7ad-692d-4f9f-82d4-221fd8e19a06)


With the change of this PR, that P tag no longer exists, so the address is just plain text, and we have extra whitespace because of linebreaks.

We can update all templates and wrap addresses around a tag in another PR.

2024-06-03 23:49 UTC, Terminator-Barbapapa commented
@MohamadNateqi Thank you for clarifying. Can you create issues in the correct repositories to update the templates?

2024-06-03 23:49 UTC, Terminator-Barbapapa approved these changes

2024-06-04 07:03 UTC, merged