New: adds full compatibility with mPDF to the Simple Template
wpovernight/woocommerce-pdf-invoices-packing-slips pull request #810
Opened 2024-05-31 13:56 UTC by alexmigf

closes #773

2024-05-31 18:07 UTC, MohamadNateqi requested changes

2024-06-02 17:01 UTC, dwalkerpriv requested changes
The documents load as usual. However, the styling issue with the `ul` and `tr` tags still is there

![mpdf enabled](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/assets/62675729/a6b6b905-886e-4adf-b99e-980076e59bfa)

Would it be better to use a tag different from the `ul` for the meta list or swap the `li` tags for `p` tags?

I've tried applying the `border-bottom` style to the `tr` tags directly but they don't get rendered, even the [doc here](https://mpdf.github.io/css-stylesheets/supported-css.html) says that these styles are compatible on table elements.

2024-06-03 07:19 UTC, alexmigf commented on templates/Simple/style.css
>  	page-break-inside: always;
It's still supported by Dompdf. We could address this in the future in another PR.

2024-06-03 07:24 UTC, alexmigf commented on templates/Simple/invoice.php
> +					<p class="item-name"><?php echo $item['name']; ?></p>
Since `<p>` is a block-level element, there should not be any text preceding the item name.

2024-06-03 09:05 UTC, alexmigf commented
@dwalkerpriv fixed

2024-06-04 12:31 UTC, MohamadNateqi approved these changes
LGTM!

I think we should have an update on the batch number plugin.
Removing `.wc-item-meta p` from the style, made it two lines:

![image](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/assets/136313810/42fc9b53-7e9c-4c30-9021-3877172b556d)

Since it's using the old format:

![image](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/assets/136313810/2dd126a0-9fd5-4494-b1b4-38c8ee33d340)

2024-06-04 13:31 UTC, alexmigf commented
@MohamadNateqi I'm not seeing a `<p>` there inside the list.

2024-06-04 14:23 UTC, MohamadNateqi commented
@alexmigf Sorry the second image was wrong. This is the correct one:

![image](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/assets/136313810/5dc7e72d-850b-4066-aa92-ad86cdfc067a)

That image was for the time the mpdf plugin was activated.

2024-06-05 04:47 UTC, dwalkerpriv approved these changes
Works well on my end now 👍

2024-06-05 08:41 UTC, alexmigf commented
@MohamadNateqi I'm not seeing any `<p>` tag currently:

![Screenshot from 2024-06-05 09-39-35](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/assets/533273/6ba32e41-f54e-412c-a386-64e511ce9d8d)

Also, mPDF extension has some code to remove the `<p>` tags here: https://github.com/wpovernight/woocommerce-pdf-ips-mpdf/blob/c407b52aad1c854b563c20f086c561d8d49df84d/wcpdf-mpdf.php#L128-L134

2024-06-05 08:48 UTC, MohamadNateqi commented
@alexmigf What if you deactivate the mPDF plugin?

2024-06-05 09:02 UTC, alexmigf commented
@MohamadNateqi that's the case, fixed.

2024-06-05 09:09 UTC, MohamadNateqi commented
@alexmigf Looks good now.

Can you also fix the difference in the indentation?

![image](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/assets/136313810/3ac635d1-b52c-4e29-b983-50d2cd566649)

2024-06-05 10:27 UTC, alexmigf commented
@MohamadNateqi fixed, also in mPDF extension too.

2024-06-05 10:57 UTC, MohamadNateqi approved these changes
Nice improvements.

2024-06-05 19:12 UTC, dwalkerpriv approved these changes
Still good on my end 👍

2024-06-28 08:30 UTC, dpeyou commented
@alexmigf when I switch to this PR and have IPS Pro active, the multilingual settings disappear from the '**Pro**' tab.

In the picture below, I cannot scroll down further.
![2024-06-28_03-23](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/assets/74280840/befb17a4-8c5e-4466-b32e-41093671cb1a)

2024-06-28 08:40 UTC, alexmigf commented
@dpeyou I have updated the branch and I don't have any issues on that regard.

2024-06-28 08:46 UTC, dpeyou commented
@alexmigf [this](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/pull/810#issuecomment-2196405771) has been resolved :heavy_check_mark:

2024-06-28 09:15 UTC, dpeyou commented
@alexmigf what is this supposed to change? I have tested it on other branches as well for both free plugins.
Is it still supposed to be relevant with this PR?

![enable rtl support - wcpdf](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/assets/74280840/77b032c3-cf28-41f8-9439-2eabbdd16e2a)

2024-06-30 23:02 UTC, YordanSoares approved these changes
I can't read Arabic, but it seems that it is working well 😁

![image](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/assets/38109855/9571bd6d-7c53-45c6-bbf3-b988d2e48469)

2024-06-30 23:06 UTC, YordanSoares commented
> But it appears that the text is wrongly placed on the document

@dpeyou did you change the template to "Simple RTL"?:

![image](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/assets/38109855/d0d86042-6dec-474a-817c-e1040c2a14b6)

2024-07-01 04:22 UTC, dpeyou commented
@YordanSoares @alexmigf  that template (Simple RTL) does not appear for me. I was under the impression that this setting was supposed to achieve that: https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/pull/810#issuecomment-2196477234

2024-07-01 04:24 UTC, dpeyou commented
![2024-06-30_23-09_1](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/assets/74280840/65a96a8c-25a2-480d-8332-ee6aa5fa8653)
![2024-06-30_23-09](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/assets/74280840/52a2d9ad-1dad-4d61-9982-3ded4d67f5a5)

2024-07-01 05:09 UTC, dpeyou commented
[screen-recording(13).webm](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/assets/74280840/6def120b-844a-4196-bc25-66c0aa4191e2)

2024-07-01 08:09 UTC, alexmigf commented
@YordanSoares I'm having the same issue as Darren, but even with lower versions of mPDF I can't get the Arabic font work. How did you tested it?

2024-07-08 14:59 UTC, alexmigf commented
@YordanSoares seems to be working for me now:

![Screenshot from 2024-07-08 15-59-20](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/assets/533273/c130d6ca-0710-4347-9ee3-bb7e12a5f7d7)

2024-07-08 15:00 UTC, alexmigf commented
@dpeyou the RTL option to work requires this branch too: https://github.com/wpovernight/woocommerce-pdf-ips-mpdf/pull/21

2024-07-08 18:49 UTC, dpeyou commented
@alexmigf take a look at [this comment](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/pull/810#issuecomment-2199204584). I was already on both correct ranches. [This video ](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/pull/810#issuecomment-2199248377)even shows that.

I will test again, and I will test on a newer test site.

2024-07-09 01:01 UTC, dpeyou commented
@alexmigf I tested on previous versions of mPDF and I think the issue is that i need to do `composer install`, to generate the templates in the free plugin.
However, when I do this command, this is the console output:

<pre><font color="#26A269"><b>$</b></font> composer install
<font color="#26A269">Installing dependencies from lock file (including require-dev)</font>
<font color="#26A269">Verifying lock file contents can be installed on current platform.</font>
<span style="background-color:#C01C28"><font color="#D0CFCC">Your lock file does not contain a compatible set of packages. Please run composer update.</font></span>

  Problem 1
    - dompdf/dompdf is locked to version v3.0.0 and an update of this package was not requested.
    - dompdf/dompdf v3.0.0 requires ext-dom * -&gt; it is missing from your system. Install or enable PHP&apos;s dom extension.
  Problem 2
    - masterminds/html5 is locked to version 2.9.0 and an update of this package was not requested.
    - masterminds/html5 2.9.0 requires ext-dom * -&gt; it is missing from your system. Install or enable PHP&apos;s dom extension.
  Problem 3
    - sabre/xml is locked to version 2.2.7 and an update of this package was not requested.
    - sabre/xml 2.2.7 requires ext-dom * -&gt; it is missing from your system. Install or enable PHP&apos;s dom extension.

To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/7.4/cli/php.ini
    - /etc/php/7.4/cli/conf.d/10-opcache.ini
    - /etc/php/7.4/cli/conf.d/10-pdo.ini
    - /etc/php/7.4/cli/conf.d/20-calendar.ini
    - /etc/php/7.4/cli/conf.d/20-ctype.ini
    - /etc/php/7.4/cli/conf.d/20-exif.ini
    - /etc/php/7.4/cli/conf.d/20-ffi.ini
    - /etc/php/7.4/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.4/cli/conf.d/20-ftp.ini
    - /etc/php/7.4/cli/conf.d/20-gd.ini
    - /etc/php/7.4/cli/conf.d/20-gettext.ini
    - /etc/php/7.4/cli/conf.d/20-iconv.ini
    - /etc/php/7.4/cli/conf.d/20-json.ini
    - /etc/php/7.4/cli/conf.d/20-mbstring.ini
    - /etc/php/7.4/cli/conf.d/20-phar.ini
    - /etc/php/7.4/cli/conf.d/20-posix.ini
    - /etc/php/7.4/cli/conf.d/20-readline.ini
    - /etc/php/7.4/cli/conf.d/20-shmop.ini
    - /etc/php/7.4/cli/conf.d/20-sockets.ini
    - /etc/php/7.4/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.4/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.4/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.4/cli/conf.d/20-tokenizer.ini
You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.</pre>

2024-07-09 06:54 UTC, alexmigf commented
@dpeyou You don't need to run composer, the vendor directory is already built: https://github.com/wpovernight/woocommerce-pdf-ips-mpdf/tree/removes-templates

You have run composer in the wrong directory, Dompdf is from the main free plugin.

2024-07-09 06:58 UTC, alexmigf commented
@dpeyou maybe you just need to install the missing Arabic translations. Check under the updates tab if you have any updates there. This was my issue too.

2024-07-09 20:03 UTC, dpeyou commented
@alexmigf  Based on your explanation, I am not sure we were having the same issue (I detailed my issue with screenschots and a video). 
- Which updates are you referring to?
- Arabic script (Saudi) is already appearing correctly on my invoice and the CSS is now applied, [after this commit](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/pull/810/commits/b2ab3ffdb2f1a8e490031efb0ac2f60b2c6f38a9), I believe.

![arabic appearing correctly after CSS fix](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/assets/74280840/b89df5f8-3032-4034-bdec-282131fe4a3e)

Previously, the Arabic text was appearing in the wrong direction, as detailed [in this comment](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/pull/810#pullrequestreview-2148897063).


The problem that I am facing now is that the Simple RTL template does not appear in the list of select-able templates - while in this PR, [as Yordan has it here](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/pull/810#issuecomment-2198794570).

2024-07-09 20:30 UTC, dpeyou commented
@alexmigf 
Just to confirm, [this setting](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/pull/810#issuecomment-2196477234) is now working well for me. This is the output (with Arabic script in the correct direction):

![arabic text](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/assets/74280840/ff87bf48-0334-49cc-82cd-54b6d2f2b852)

I am currently thinking that the issue you mentioned in our last Wednesday meeting and that [you mention here](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/pull/810#issuecomment-2216747652) is not related to this PR, right? The Arabic script above does not appear wihtout mPDF, so it appears to me the plugin is doing its job correctly, despite the error I mentioned in my previous comment.

2024-07-09 23:37 UTC, dpeyou commented
I should have shared the Invoice itself set to Arabic (Saudi) instead of just demonstrating manually added Arabic script:

![2024-07-09_18-27](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/assets/74280840/dac2152c-770c-4c6a-a198-0db8a7693587)


There are still no RTL templates in the plugin settings, as in described in Yordan's comment:
https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/pull/810#issuecomment-2198794570

2024-07-10 07:54 UTC, alexmigf commented
@dpeyou the mPDF templates have been removed in this [PR](https://github.com/wpovernight/woocommerce-pdf-ips-mpdf/pull/21). We are now using the default templates, which support mPDF out-of-the-box. If you need RTL, you can enable it in the General tab settings.

2024-07-10 08:07 UTC, dpeyou commented
@alexmigf thanks for clarifying. That means this is good to go 😀

2024-07-10 08:08 UTC, dpeyou approved these changes
Good to go :rocket:  Does this need documenting?

2024-07-10 08:35 UTC, alexmigf commented
@dpeyou doesn't hurt I think. Maybe a general page explaining why mPDF is an alternative engine, and for which customers is better (including the RTL setting).

2024-10-07 08:35 UTC, merged