Fix preview issue
wpovernight/woocommerce-pdf-invoices-packing-slips pull request #833
Opened 2024-07-12 12:00 UTC by MohamadNateqi

This PR aims to fix three issues on preview:

1. Number format: The document setting for the preview process was `null`, which is fixed, and now number formats are applied.
2. Date: The preview was not updated based on the `display_date` setting, which is fixed by introducing a new `initiate_date` and calling it during the preview process.
3. Number: The preview was not updated based on the `display_number` setting, which is fixed by introducing a new `generate_document_number` and calling it during the preview process.

2024-08-13 08:18 UTC, alexmigf requested changes

2024-08-13 08:18 UTC, alexmigf commented on includes/documents/abstract-wcpdf-order-document.php
> +	public function generate_document_number( bool $increment_document_number = false ) {
Maybe just `$increment` is enough?

2024-08-13 08:18 UTC, alexmigf commented on includes/documents/abstract-wcpdf-order-document.php
> +	public function initiate_date(): void {
Maybe you could add DocBlocks?

2024-08-13 09:19 UTC, alexmigf requested changes

2024-08-13 09:19 UTC, alexmigf commented on includes/documents/abstract-wcpdf-order-document-methods.php
> +			$document_display_date = $document_settings['display_date'] ?? 'document_date';
Old Invoices still use `invoice_date`, you need to accommodate that too.

2024-08-13 09:19 UTC, alexmigf commented on includes/documents/abstract-wcpdf-order-document-methods.php
> +			'document_date' => __( 'Document Date', 'woocommerce-pdf-invoices-packing-slips' ),
I think having "Invoice Date" is preferable, maybe using the document object title?

2024-08-13 10:28 UTC, alexmigf approved these changes
LGTM!

2024-08-13 10:33 UTC, alexmigf commented
@MohamadNateqi the Premium Templates needs to be updated on the `document_date` change: https://github.com/search?q=repo%3Awpovernight%2Fwoocommerce-pdf-ips-templates+invoice_date&type=code

2024-08-16 11:24 UTC, alexmigf commented
@MohamadNateqi can you fix the conflicts here?

2024-08-16 11:49 UTC, MohamadNateqi commented
@alexmigf Done.

2024-10-09 15:17 UTC, alexmigf commented
@MohamadNateqi can you fix the conflicts again please?

2024-10-09 16:35 UTC, MohamadNateqi commented
@alexmigf Done.

2025-01-23 11:35 UTC, alexmigf commented
@MohamadNateqi could you fix the conflicts here please?

2025-04-02 08:38 UTC, alexmigf requested changes

2025-04-02 08:38 UTC, alexmigf commented on includes/Documents/OrderDocument.php
> +	public function generate_document_number( bool $increment = false ) {
Maybe `get_` would be more appropriated?

2025-04-02 09:50 UTC, alexmigf commented on includes/Documents/OrderDocument.php
> +	public function generate_document_number( bool $increment = false ) {
I could get on board with that, but in that case, we should remove the `$increment` parameter and the `get_next()` part, since it seems like two different concepts are being mixed here.

2025-04-02 13:23 UTC, MohamadNateqi commented on includes/Documents/OrderDocument.php
> +	public function generate_document_number( bool $increment = false ) {
Understand, you're right.

In this case, I think we have the following options:
1. Rename it to something like this: `get_or_generate_document_number`.
2. Using `get_` as you said.

Both options look good to me. Which do you prefer?

2025-04-02 13:35 UTC, alexmigf commented on includes/Documents/OrderDocument.php
> +	public function generate_document_number( bool $increment = false ) {
Why not 2 separated functions? Just an idea, but let me know.

2025-04-02 14:12 UTC, MohamadNateqi commented on includes/Documents/OrderDocument.php
> +	public function generate_document_number( bool $increment = false ) {
I may not fully share your vision, but two functions may create more hassle and be less clean than one.

Abstracting away the conditional boilerplate from the caller and having a single method that encapsulates both might be better.

Also, it might be simpler for third parties to interrupt the process of obtaining document numbers and modify the data since we're only incrementing the document number if third parties are not assigning a number already.

Although the one-function approach is simple, I agree that it violates SRP and does two jobs in one function.

2025-04-02 14:20 UTC, alexmigf commented on includes/Documents/OrderDocument.php
> +	public function generate_document_number( bool $increment = false ) {
We just an idea that came to my mind while writing my reply. Just `get_` makes more sense to me, because even if you are incrementing you are getting a new number.

2025-04-03 08:29 UTC, alexmigf requested changes

2025-04-03 08:29 UTC, alexmigf commented on includes/Documents/OrderDocument.php
> +	public function get_document_number( bool $increment = false ) {
Maybe `$increment` could be `$generate`? What do you think?

2025-04-09 11:33 UTC, merged