New: automatic cleanup of unlocked Semaphore locks. Other improvements.
wpovernight/woocommerce-pdf-invoices-packing-slips pull request #856
Opened 2024-09-03 10:47 UTC by alexmigf

closes #854

2024-09-03 13:00 UTC, MohamadNateqi commented
I wonder if the "unlocked locks" combination could be a little confusing. What do you think about "released locks"?

2024-09-03 13:15 UTC, MohamadNateqi requested changes

2024-09-03 13:15 UTC, MohamadNateqi commented on includes/class-wcpdf-updraft-semaphore.php
> +	private static function get_hook_name(): string {
What do you think about `get_cleanup_hook_name()`?

2024-09-03 13:15 UTC, MohamadNateqi commented on includes/class-wcpdf-updraft-semaphore.php
> +	public static function get_cleanup_action() {
Return type declaration.

2024-09-03 13:15 UTC, MohamadNateqi commented on includes/class-wcpdf-updraft-semaphore.php
> +			$interval = apply_filters( self::get_hook_name() . '_interval', 30 * DAY_IN_SECONDS ); // default: every 30 days
Would it be useful to provide a filter for the days?

2024-09-03 13:49 UTC, MohamadNateqi commented on includes/class-wcpdf-updraft-semaphore.php
> +			$interval = apply_filters( self::get_hook_name() . '_interval', 30 * DAY_IN_SECONDS ); // default: every 30 days
Sorry, my mistake. No problem, all good.

2024-09-03 14:13 UTC, MohamadNateqi approved these changes
LGTM!

2024-09-06 23:32 UTC, DavidAnderson684 approved these changes

2024-09-09 08:45 UTC, merged