New: Simple template titles registration improvement
wpovernight/woocommerce-pdf-invoices-packing-slips pull request #867
Opened 2024-09-30 15:08 UTC by alexmigf

2024-10-02 17:11 UTC, MohamadNateqi requested changes

2024-10-03 14:31 UTC, alexmigf commented on includes/wcpdf-functions.php
> +function wpo_wcpdf_get_simple_template_default_table_headers( $document ): array {
This is only used in the Simple Template, the other templates use `wpo_wcpdf_templates_get_table_headers()`. I don't have a preference, but what you think?

2024-10-03 14:32 UTC, alexmigf commented on includes/documents/class-wcpdf-packing-slip.php
> +	public $output_formats;
What do you mean?

2024-10-03 14:35 UTC, alexmigf commented on templates/Simple/invoice.php
> +					printf( '<th class="%s"><span>%s</span></th>', $column_class, $column_title );
I'm just following the same pattern as the Premium Templates, but I will remove.

2024-10-03 14:37 UTC, MohamadNateqi commented on includes/wcpdf-functions.php
> +function wpo_wcpdf_get_simple_template_default_table_headers( $document ): array {
My idea was to make it a general function so customers can also use it for their custom templates. I'm OK with this too.

2024-10-03 14:39 UTC, MohamadNateqi commented on includes/documents/class-wcpdf-packing-slip.php
> +	public $output_formats;
These properties already declared in the parent class, so I think maybe we can not declare them again here?

2024-10-03 15:03 UTC, MohamadNateqi approved these changes
LGTM!

2024-10-03 15:47 UTC, merged