Updating the setup Wizard
wpovernight/woocommerce-pdf-invoices-packing-slips pull request #895
Opened 2024-10-25 05:38 UTC by BrunoPavlinic98

closes #857

2024-10-25 05:42 UTC, BrunoPavlinic98 commented
@Terminator-Barbapapa Here is the initial version. I think this is quite of a progress in terms of design. On the final step, the user gets redirected to the upgrade page after he clicks the "Finish" button.

2024-11-06 10:24 UTC, BrunoPavlinic98 commented
@Terminator-Barbapapa I have added enhanced select.

I have deliberately added the following lines:
```
<link rel="stylesheet" href="<?php echo WC()->plugin_url() . '/assets/css/admin.css'; ?>">
<script src="<?php echo WC()->plugin_url() . '/assets/js/select2/select2.full.min.js'; ?>"></script>
```
because for some reason, `wp_enqueue_style`, `wp_register_script`, and `wp_enqueue_style` did not work for me.

With that, I am not sure why JS minifying is not working, I will try to reboot it.

2025-01-24 14:41 UTC, alexmigf requested changes

2025-01-24 14:41 UTC, alexmigf commented on includes/SetupWizard.php
> +			<link rel="stylesheet" href="<?php echo WC()->plugin_url() . '/assets/css/admin.css'; ?>">
You need to enqueue these two assets and then print them here using `wp_print_scripts`. Refer to the example on lines `150` and `151`.

2025-01-24 14:41 UTC, alexmigf commented on includes/SetupWizard.php
> +			array( 'dashicons', 'install' ),
Are these dependencies in use?

2025-01-24 14:41 UTC, alexmigf commented on views/setup-wizard/attach-to.php
> +		'default'         => isset( $current_settings['attach_to_email_ids'] ) ? array_keys( array_filter( $current_settings['attach_to_email_ids'], function( $value ) { return $value === '1'; } ) ) : arra
I'm unsure if we should provide a default here, as it's not something we do in the settings.

2025-01-24 14:41 UTC, alexmigf commented on includes/SetupWizard.php
> +			<link rel="stylesheet" href="<?php echo WC()->plugin_url() . '/assets/css/admin.css'; ?>">
Can you clarify the purpose of the `admin.css` file?

2025-01-27 09:31 UTC, BrunoPavlinic98 commented on includes/SetupWizard.php
> +			<link rel="stylesheet" href="<?php echo WC()->plugin_url() . '/assets/css/admin.css'; ?>">
@alexmigf With the new implementation, I don't even need to print the styles.

2025-01-27 09:32 UTC, BrunoPavlinic98 commented on includes/SetupWizard.php
> +			<link rel="stylesheet" href="<?php echo WC()->plugin_url() . '/assets/css/admin.css'; ?>">
We need `admin.css` for enhanced select styles.

2025-01-27 09:57 UTC, alexmigf requested changes

2025-01-27 09:57 UTC, alexmigf commented on includes/SetupWizard.php
>  			WPO_WCPDF_VERSION
Maybe this could be the Woo version.

2025-01-27 09:57 UTC, alexmigf commented on includes/SetupWizard.php
>  			<script src="<?php echo WC()->plugin_url() . '/assets/js/select2/select2.full.min.js'; ?>"></script>
Could you consider enqueuing this properly as well?

2025-01-27 11:08 UTC, BrunoPavlinic98 commented on includes/SetupWizard.php
>  			<script src="<?php echo WC()->plugin_url() . '/assets/js/select2/select2.full.min.js'; ?>"></script>
Done!

2025-01-27 11:20 UTC, alexmigf requested changes

2025-01-27 17:01 UTC, alexmigf requested changes
The "Set image" doesn't seem to be working as expected:

> Uncaught TypeError: $settings_wrapper.parent().block is not a function

2025-01-29 07:26 UTC, BrunoPavlinic98 commented
> The "Set image" doesn't seem to be working as expected:
> 
> > Uncaught TypeError: $settings_wrapper.parent().block is not a function

@alexmigf Fixed! jQuery blockui was not added, that is the reason for the error.

2025-01-29 08:06 UTC, alexmigf requested changes
I already have an image set, but it doesn't display when I run the wizard.

![Screenshot from 2025-01-29 08-05-24](https://github.com/user-attachments/assets/eaa12578-9e94-4e0e-8600-ad713c1d3319)

2025-01-29 08:10 UTC, alexmigf commented
@BrunoPavlinic98 I tried again, and it seems to be working now. I'm not sure if caching was the issue, even though I cleared it before running the test.

2025-01-29 08:18 UTC, alexmigf requested changes
I installed this branch on a different local setup and found a conflict with the [Discount Rules for WooCommerce](https://wordpress.org/plugins/woo-discount-rules/) plugin. We should find a way to prevent this, as other plugins might use a similar approach.

![Screenshot from 2025-01-29 08-14-58](https://github.com/user-attachments/assets/fd40ecda-fee7-4923-8ffd-399ee3a7ddd8)

2025-01-29 08:48 UTC, BrunoPavlinic98 commented
> I installed this branch on a different local setup and found a conflict with the [Discount Rules for WooCommerce](https://wordpress.org/plugins/woo-discount-rules/) plugin. We should find a way to prevent this, as other plugins might use a similar approach.
> 
> ![Screenshot from 2025-01-29 08-14-58](https://private-user-images.githubusercontent.com/533273/407653141-fd40ecda-fee7-4923-8ffd-399ee3a7ddd8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzgxNDAyNjAsIm5iZiI6MTczODEzOTk2MCwicGF0aCI6Ii81MzMyNzMvNDA3NjUzMTQxLWZkNDBlY2RhLWZlZTctNDkyMy04ZmZkLTM5OWVlM2E3ZGRkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEyOVQwODM5MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNjRhODdmMWQ4ZTY3NTVhZmU3NTJmNDk2Y2FkZTljYjFhNzEwOGMzZWZkNmIyNzU3M2U5OTAwOTNiYTIxMzc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.IVUR2k6IrulShM8C5RVMKYFUe3zGSebt27rynbm82xo)

@alexmigf How to I reproduce this behaviour? I installed that plugin, but I don't see the extra content.

2025-01-29 09:36 UTC, alexmigf commented
@BrunoPavlinic98 I have implemented a permanent fix for the issue.

2025-01-29 09:47 UTC, BrunoPavlinic98 commented
> @BrunoPavlinic98 I have implemented a permanent fix for the issue.

@alexmigf Nice, I saw it. I think it is ready for review again.

2025-01-29 10:01 UTC, alexmigf commented
@BrunoPavlinic98 I believe [this](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/pull/895#issuecomment-2620947326) issue warrants a more thorough review, especially since @Terminator-Barbapapa  has also [observed](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/pull/895#issuecomment-2620962676) the same behavior.

2025-01-29 11:07 UTC, BrunoPavlinic98 commented
> @BrunoPavlinic98 I believe [this](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/pull/895#issuecomment-2620947326) issue warrants a more thorough review, especially since @Terminator-Barbapapa has also [observed](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/pull/895#issuecomment-2620962676) the same behavior.

@alexmigf @Terminator-Barbapapa I tried to replicate this multiple times with cache cleaning, without in, in incognito windows and normal ones, but without luck.
Did you do anything else except the steps already described?

2025-01-29 11:58 UTC, alexmigf commented
Try this:

1. Switch to the `main` branch.  
2. Navigate to **PDF Invoices > General** and check if a logo is set. If not, add one.  
3. Click **Save Changes**.  
4. Switch to the `857-setup-wizard-update` branch.  
5. Clear your browser cache.  
6. Go to **PDF Invoices > Tools > Run the Setup Wizard**.  
7. Proceed to Step 2 and observe that the logo is missing.

2025-01-29 12:14 UTC, BrunoPavlinic98 commented
> @BrunoPavlinic98 Try this:
> 
> 1. Switch to the `main` branch.
> 2. Navigate to **PDF Invoices > General** and check if a logo is set. If not, add one.
> 3. Click **Save Changes**.
> 4. Switch to the `857-setup-wizard-update` branch.
> 5. Clear your browser cache.
> 6. Go to **PDF Invoices > Tools > Run the Setup Wizard**.
> 7. Proceed to Step 2 and observe that the logo is missing.

@alexmigf Tried multiple times, but I don't have any issues. This happens on your environment every time you try?

2025-01-29 12:28 UTC, alexmigf commented
@BrunoPavlinic98 no, only for the first try. I will debug and fix it, if you don't mind.

2025-01-29 12:39 UTC, BrunoPavlinic98 commented
> @BrunoPavlinic98 no, only for the first try. I will debug and fix it, if you don't mind.

@alexmigf If you have a solution, sure, I don't mind since I can't replicate this.

2025-01-29 13:31 UTC, alexmigf commented
@BrunoPavlinic98 this was missing: https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/pull/895/commits/2562ba32e804614a92a78c96d7dc802626694481#diff-e268583d2c221dba966bff13b95da8756b094132176e33cb049a07e91305aa52R15

Should be fixed now.

2025-01-29 13:38 UTC, BrunoPavlinic98 commented
> @BrunoPavlinic98 this was missing: [2562ba3#diff-e268583d2c221dba966bff13b95da8756b094132176e33cb049a07e91305aa52R15](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/commit/2562ba32e804614a92a78c96d7dc802626694481#diff-e268583d2c221dba966bff13b95da8756b094132176e33cb049a07e91305aa52R15)
> 
> Should be fixed now.

@alexmigf That is why I could not replicate it, I have a fresh setup and did not setup multilingual setup.
@Terminator-Barbapapa Can you also please confirm it is working?

2025-01-29 13:51 UTC, alexmigf commented
@BrunoPavlinic98 I didn't had a multilingual setup either.

2025-01-31 15:40 UTC, Terminator-Barbapapa commented
I think the enhanced select should follow the new color scheme. Currently it looks like this:

<img width="953" alt="Scherm­afbeelding 2025-01-31 om 16 24 44" src="https://github.com/user-attachments/assets/acbb7d4b-5ae3-4d90-9cf6-7f9842f7d6b4" />

But I think it should look like this:

<img width="1006" alt="Scherm­afbeelding 2025-01-31 om 16 37 21" src="https://github.com/user-attachments/assets/046c6750-3496-4d8d-aa96-cc7a58a8e8cd" />

For the selected elements you can use:

```
background-color: #6e1edc;
border-bottom: 1px solid white;
color: white;
```

And for the hover you can use:

```
background-color: #f1e9fc;
color: #000;
```

2025-01-31 15:42 UTC, Terminator-Barbapapa commented
The 'Finish' link at the end should point to the 'General' settings tab, and not to the 'Upgrade' tab as discussed. We should add an upgrade section in the final step of the Wizard, but we can do that in a separate issue.

2025-02-03 07:56 UTC, BrunoPavlinic98 commented
> I think the enhanced select should follow the new color scheme. Currently it looks like this:
> 
> <img alt="Scherm­afbeelding 2025-01-31 om 16 24 44" width="953" src="https://private-user-images.githubusercontent.com/19350150/408624927-acbb7d4b-5ae3-4d90-9cf6-7f9842f7d6b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzg1Njc4OTAsIm5iZiI6MTczODU2NzU5MCwicGF0aCI6Ii8xOTM1MDE1MC80MDg2MjQ5MjctYWNiYjdkNGItNWFlMy00ZDkwLTljZjYtN2Y5ODQyZjdkNmI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjAzVDA3MjYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4YjUxMDllNjNhZWJhOTVhMGI1YzAwMjc5NmMwNWMxZmYyYzY3NTA5YTIxZDAyNTQzNGNhNWYzNjJlNjc0NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GQ05dtkQPbyYZfgf8R_LuwEnfgftvfxIAr8PKfUMfjo">
> But I think it should look like this:
> 
> <img alt="Scherm­afbeelding 2025-01-31 om 16 37 21" width="1006" src="https://private-user-images.githubusercontent.com/19350150/408625049-046c6750-3496-4d8d-aa96-cc7a58a8e8cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzg1Njc4OTAsIm5iZiI6MTczODU2NzU5MCwicGF0aCI6Ii8xOTM1MDE1MC80MDg2MjUwNDktMDQ2YzY3NTAtMzQ5Ni00ZDhkLWFhOTYtY2M3YTU4YThlOGNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjAzVDA3MjYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyN2UwYTBhOGZmMzczODEyY2YzNzQwOWQ4NmUwMDUyMWM2ZTIzZGQ3ZTllMDY2ZjY5MzY1YWQxM2Y2YzY5NmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xK5OpJ6KGYyf6xquI9CM_CSfSQgX9uxv9d3D94BjZGY">
> For the selected elements you can use:
> 
> ```
> background-color: #6e1edc;
> border-bottom: 1px solid white;
> color: white;
> ```
> 
> And for the hover you can use:
> 
> ```
> background-color: #f1e9fc;
> color: #000;
> ```

@Terminator-Barbapapa Done! I have only removed the border bottom styling because it moved the elements 1px above on hover, which looked weird.

2025-02-03 08:44 UTC, Terminator-Barbapapa approved these changes

2025-02-03 08:49 UTC, alexmigf approved these changes

2025-02-03 09:28 UTC, MohamadNateqi approved these changes
LGTM!

2025-02-03 09:28 UTC, MohamadNateqi commented on assets/css/setup-wizard.css
> +	border-color: none!important;
It should be `unset`. 
Also, a space before `!important` would be good, same for other occurance.

2025-02-03 09:28 UTC, MohamadNateqi commented on views/setup-wizard/attach-to.php
> +		'default'         => isset( $current_settings['attach_to_email_ids'] ) ? array_keys( array_filter( $current_settings['attach_to_email_ids'], function( $value ) { return $value === '1'; } ) ) : arra
Maybe it would be good to extract this into a separate variable to improve readability.

2025-02-03 11:13 UTC, merged