Admin notice for requirements
wpovernight/woocommerce-pdf-invoices-packing-slips pull request #902
Opened 2024-10-31 11:27 UTC by MohamadNateqi

close #893

2024-11-21 08:36 UTC, alexmigf requested changes
GMagick or IMagick is only recommended, but I still have the notice showing:

![Screenshot from 2024-11-21 08-36-08](https://github.com/user-attachments/assets/5b1aa7fa-9022-45f8-9897-ad128ca81655)

2024-11-21 08:36 UTC, alexmigf commented on includes/Main.php
> +			'<strong>WooCommerce PDF Invoices & Packing Slips</strong>',
This name is wrong.

2024-11-21 09:19 UTC, alexmigf reviewed
There's an issue with this implementation: the notice still appears even after meeting the requirements, as long as you don't visit the status page. I believe we should refactor the logic to separate it from the view.

2024-11-22 08:58 UTC, alexmigf requested changes
This branch doesn't include the submodule. Perhaps you could copy your changes to a new one? I'm unsure if merging with the main branch would be seamless.

2024-11-22 08:58 UTC, alexmigf commented on includes/Settings/SettingsDebug.php
> +		if ( ! $server_configs['PHP version']['result'] ) {
I believe this section can be removed, as promoting PHP 5 is no longer necessary or recommended.

2024-11-22 08:58 UTC, alexmigf commented on views/advanced-status.php
> +$server_configs = $this->get_server_config();
Maybe you could pass this variable from `display_status()` or `output()`.

2024-11-22 09:32 UTC, MohamadNateqi commented
@alexmigf It seems the submodule is included in this branch, can you also check?

2024-11-22 09:51 UTC, alexmigf approved these changes
Good job!

2024-11-22 09:53 UTC, merged