Fix postcode and city defaults in UBL tax output
wpovernight/woocommerce-pdf-invoices-packing-slips pull request #962
Opened 2024-12-31 12:32 UTC by alexmigf

closes #961

2025-01-01 12:33 UTC, MohamadNateqi requested changes

2025-01-01 12:33 UTC, MohamadNateqi commented on ubl/Settings/TaxesSettings.php
> +							$postcode        = array();
Could you please explain to me why this changed to an array?
Since the query is getting all tax locations for a `tax_rate_id`, and the `tax_rate_id` seems to be unique in the `wp_woocommerce_tax_rates` table, so how can we have several tax locations for one tax rate?

2025-01-01 12:33 UTC, MohamadNateqi commented on ubl/Settings/TaxesSettings.php
>  							$reason   = isset( $this->settings['rate'][ $result->tax_rate_id ]['reason'] )   ? $this->settings['rate'][ $result->tax_rate_id ]['reason']   : '';
Replacing the empty string with a `*` would be good.

2025-01-02 09:55 UTC, alexmigf commented on ubl/Settings/TaxesSettings.php
> +							$postcode        = array();
The `tax_rate_id` is unique in `wp_woocommerce_tax_rates`, but in `wp_woocommerce_tax_rate_locations`, it allows multiple entries to associate one tax rate with multiple locations (e.g., postcodes or cities). This is why `$postcode` is an array—it captures all postcodes linked to the same tax rate.

2025-01-02 09:56 UTC, alexmigf commented on ubl/Settings/TaxesSettings.php
>  							$reason   = isset( $this->settings['rate'][ $result->tax_rate_id ]['reason'] )   ? $this->settings['rate'][ $result->tax_rate_id ]['reason']   : '';
Why? Keep in mind that these variables are used in selectors.

2025-01-02 10:11 UTC, MohamadNateqi commented on ubl/Settings/TaxesSettings.php
>  							$reason   = isset( $this->settings['rate'][ $result->tax_rate_id ]['reason'] )   ? $this->settings['rate'][ $result->tax_rate_id ]['reason']   : '';
I thought it's better to show a `*` instead of an empty string here:

![image](https://github.com/user-attachments/assets/81f356a9-240f-48f4-a0ca-5cefa4594393)

Same as WooCommerce.

2025-01-02 10:18 UTC, alexmigf commented on ubl/Settings/TaxesSettings.php
>  							$reason   = isset( $this->settings['rate'][ $result->tax_rate_id ]['reason'] )   ? $this->settings['rate'][ $result->tax_rate_id ]['reason']   : '';
Done.

2025-01-02 10:20 UTC, MohamadNateqi approved these changes
All good!

2025-01-02 10:25 UTC, merged