Add global helper functions for UBL
wpovernight/woocommerce-pdf-invoices-packing-slips pull request #963
Opened 2024-12-31 12:48 UTC by MohamadNateqi

close #926

2024-12-31 14:21 UTC, alexmigf reviewed
Would a single function suffice? For example:

```php
function wpo_ips_ubl_sanitize_string( $string ) {
	$string  = wp_strip_all_tags( $string );
	$decoded = htmlspecialchars_decode( $string, ENT_QUOTES );           // Decode wtexturize effects.
	return htmlspecialchars( $decoded, ENT_XML1 | ENT_QUOTES, 'UTF-8' ); // Escape for XML.
}
```

2025-01-01 15:10 UTC, MohamadNateqi commented
Applying the last `htmlspecialchars()` makes the output wrong:

![image](https://github.com/user-attachments/assets/bd13f3ee-55f1-42a7-bd5f-d5bb1aa37d08)

![image](https://github.com/user-attachments/assets/cc5898e0-8ddd-4c4d-891a-8ab37dff18ad)

![image](https://github.com/user-attachments/assets/28e30442-5faa-40df-8507-e64fce344c24)

As you can see there are two `&amp;` while it should be one. Same for the address. If I'm not wrong, the `sabre` library also applies a conversation that causes this, so I think returning the value without `htmlspecialchars()` is enough.

2025-01-02 09:46 UTC, alexmigf requested changes
You forgot to apply the function here:

https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/9b452971dc1942905e4157a4038ff52dbeeb3ffe/ubl/Handlers/Common/AddressHandler.php#L206-L240

2025-01-02 09:46 UTC, alexmigf commented on ubl/Handlers/Common/AdditionalDocumentReferenceHandler.php
> +								'filename' => ! empty( $this->document->order_document->get_filename() ) ? wpo_ips_ubl_sanitize_string( $this->document->order_document->get_filename() ) : '',
Maybe here is not required.

2025-01-02 09:46 UTC, alexmigf commented on ubl/Handlers/Common/AdditionalDocumentReferenceHandler.php
> +						'value' => ! empty( $this->document->order_document->get_number() ) ? wpo_ips_ubl_sanitize_string( $this->document->order_document->get_number()->get_formatted() ) : '',
Here too.

2025-01-02 09:46 UTC, alexmigf commented on ubl/Handlers/Common/AddressHandler.php
> +		$vat_number = ! empty( $this->document->order_document ) ? wpo_ips_ubl_sanitize_string( $this->document->order_document->get_shop_vat_number() ) : '';
Here too.

2025-01-02 09:46 UTC, alexmigf commented on ubl/Handlers/Common/AddressHandler.php
> +		$coc_number = ! empty( $this->document->order_document ) ? wpo_ips_ubl_sanitize_string( $this->document->order_document->get_shop_coc_number() ) : '';
Here too.

2025-01-02 09:46 UTC, alexmigf commented on ubl/Handlers/Common/IdHandler.php
> +			'value' => wpo_ips_ubl_sanitize_string( $this->document->order_document->get_number()->get_formatted() ),
Here too.

2025-01-02 10:27 UTC, alexmigf commented on wpo-ips-ubl-functions.php
> +| UBL Document global getter functions
Maybe remove "getter".

2025-01-02 10:27 UTC, alexmigf requested changes

2025-01-02 10:27 UTC, alexmigf commented on wpo-ips-ubl-functions.php
> +use WPO\IPS\Documents\OrderDocument;
Not being used.

2025-01-02 10:51 UTC, alexmigf requested changes
Maybe we could also apply the function here:

https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/7e5cd7d4bf3ce6ade6854e62a7047c6a04607ca6/ubl/Handlers/Common/AddressHandler.php#L62-L73

https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/7e5cd7d4bf3ce6ade6854e62a7047c6a04607ca6/ubl/Handlers/Common/AddressHandler.php#L203

https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/7e5cd7d4bf3ce6ade6854e62a7047c6a04607ca6/ubl/Handlers/Common/AddressHandler.php#L268

2025-01-02 10:51 UTC, alexmigf commented on ubl/Handlers/Common/AddressHandler.php
> +		$address    = ! empty( $this->document->order_document ) ? wpo_ips_ubl_sanitize_string( $this->document->order_document->get_shop_address() ) : get_option( 'woocommerce_store_address' );
I would apply the function solely to the output; otherwise, the fallback won't be handled properly.

By doing so, I would also apply the same approach to `$company` to maintain consistency.

2025-01-02 11:30 UTC, alexmigf approved these changes
LGTM!

2025-01-02 11:32 UTC, alexmigf commented
@MohamadNateqi Renaming the file to `wpo-ips-functions-ubl.php` might be a better option, allowing it to stay organized with similar files in the root directory:

![Screenshot from 2025-01-02 11-32-33](https://github.com/user-attachments/assets/ad12a5f0-c69a-4c41-a4da-8da80c585cda)

2025-01-02 11:39 UTC, MohamadNateqi commented
@alexmigf Done.
You practically did everything on this task. 😅

2025-01-02 11:40 UTC, alexmigf requested changes

2025-01-02 11:40 UTC, alexmigf commented on woocommerce-pdf-invoices-packingslips.php
> +		include_once $this->plugin_path() . '/wpo-ips-functions_ubl.php';
Not underscore.

2025-01-02 11:57 UTC, merged